### PR TITLE
Add Support for Docker Secrets

### PR DESCRIPTION
**Pull request by jamiejackson**
This is a work in progress. I'm trying to get the image to support Docker secrets.

[Here's an explanation](https://github.com/jamiejackson/docker-commandbox/blob/docker-secrets/TEMP_README.md) of where I am. I'm having trouble getting automated tests going with this. However, it's possible that the image itself would actually work properly if it were run directly (I haven't tried that yet.)

1. Could you comment on the idea and whether there's an interest in this?
2. Suggestions as to getting the automated tests running? (Assuming they're even relevant, since the test script does things kinda differently than a real container being started fresh.)

### CODE REVIEW

**Comment by bdw429s** [comment]
@jclausen Can you weigh in here?

**Comment by jclausen** [comment]
@jamiejackson :  I'm _totally_ for implementing some sort of Docker secrets support.  

As far as tests are concerned, the only one I'm looking at passing to evaluate a pull request is the build with the root-level `Dockerfile` and the Alpine build.  Since the engine-level builds pull the `ortussolutions/commandbox` image, they are going to fail if run in `development`, since the tests are based on the state of this branch.  

All of my container build tests only check  environment variable statuses anyway. You can look at `tests.sh` to see how those are implemented.  If you just run `docker build ./` from the root of the site, though, you can play with the generated image for all of your specific testing needs.

**Comment by jclausen** [comment]
BTW, When I want to run the tests for the whole container, I just run the travis build:

```
export BUILD_IMAGE_DOCKERFILE=Dockerfile 
export BUILD_IMAGE_TAG=ortussolutions/commandbox
docker-compose -f docker-compose.test.yml up --build --exit-code-from sut
```

That will exit non-zero if there is an error

**Comment by jamiejackson** [comment]
This branch needs to be cleaned up (it's got cruft from my attempts at integrating with the test scripts, etc.), but it does seem to work with secrets and a `myconfig.json`.

```
BUILD_IMAGE_DOCKERFILE=Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox docker-compose -f docker-compose.secret-test.yml up --build
```

The proof is that the admin (http://localhost:8080/lucee/admin/web.cfm) will have the password `secretvalue`, which comes from the `test_docker_secret` Docker secret.

Got feedback?

BTW, it would be nice to have test coverage around this, but since it doesn't seem to tie in very well to the existing test script, I think it would need something different.

**Comment by jclausen** [comment]
@jamiejackson : The type of test coverage you've implemented in `build/tests/test.cfconfig.env.sh`, with a few extra lines in the test should cover what we need to test for the image functionality.  CommandBox already has test coverage for the use of environment variables in `server.json` and Docker already has tests for secrets, so our job would be to test that the environment variable is being picked up by testing the environment variable value and then the `cfconfig` file application in the server startup test.

That said, I'm feeling a bit concerned that implementation may introduce some additional potential for failure or unexpected results.  The directory scanning here, for example, is vulnerable to blowing up or inadvertently expanding the environment if the contents of the secret are anything more than a simple value:  https://github.com/Ortus-Solutions/docker-commandbox/pull/11/files#diff-61b4862dba2d96d8b2d36a81a83ed077R19   The `env_secret_expand` method will need some additional protection from complexity in the secret content.  (e.g. = `export "$var"=${val@Q}` )

Should it also exit non-zero after the error message if the the environment variable remains `{DOCKER-SECRET:...}` https://github.com/Ortus-Solutions/docker-commandbox/pull/11/files#diff-61b4862dba2d96d8b2d36a81a83ed077R29 ?

**Comment by jamiejackson** [comment]
> That said, I'm feeling a bit concerned that implementation may introduce some additional potential for failure or unexpected results. The directory scanning here, for example, is vulnerable to blowing up or inadvertently expanding the environment if the contents of the secret are anything more than a simple value: https://github.com/Ortus-Solutions/docker-commandbox/pull/11/files#diff-61b4862dba2d96d8b2d36a81a83ed077R19 The env_secret_expand method will need some additional protection from complexity in the secret content. (e.g. = export "$var"=${val@Q} )

Could you describe a couple of test cases so I could try to elicit the potential bad behavior?
> Should it also exit non-zero after the error message if the the environment variable remains {DOCKER-SECRET:...} https://github.com/Ortus-Solutions/docker-commandbox/pull/11/files#diff-61b4862dba2d96d8b2d36a81a83ed077R29 ?

I'm not sure if it should behave like a missing environment variable (replace the token with empty string) or whether it should exit non-zero. I'd guess that most (all?) of the time that a missing secret shouldn't be ignored (an argument for non-zero), but I'm not sure I have all the use cases in mind.

**Comment by jclausen** [comment]
Hmm.  Sorry @jamiejackson : I thought I had replied to your question on the bad behavior.  Maybe I started replying and then something came up.  What I was concerned about is this line:

```
val=$(cat "${secret}")
export "$var"="$val"
``` 

I went through, though, and performed some tests and, since it's very difficult to get bash to execute anything that is brought in via cat, I think my concern was unfounded.  If you'd like to clean up this pull request in to the essentials, I'd like to add it to the next release.

**Comment by jamiejackson** [comment]
Sure, I'll try to get to it in the next few days. Here's my plan; let me know if there's anything you want to tweak:

* A missing secret that is referenced will be given a value of empty string--the same way that environment variables work.
* (As I mentioned at the outset) I was unable to get automated tests to work in the context of the existing ones, so I'll be stripping that stuff out.

**Comment by jclausen** [comment]
Sounds like a plan @jamiejackson .  Tell you what: Go ahead and implement it and I'll figure out the test coverage.  There may be some additional things we need to add to the entire process that would cover other areas that are missing.

**Comment by jamiejackson** [comment]
Okay, it's cleaned up.

**Comment by jclausen** [comment]
@jamiejackson : I just wanted to give you a heads-up that I had to push a change up to master this evening to change the placeholder syntax for the secrets.  The curly braces were not compatible with CLI commands used in Docker swarm ( and swarm managers ) and were trying to evaluate the contents as an environment variable.   In addition the dash in `DOCKER-SECRET` was throwing an error on evaluation.  The new syntax is:

`<<SECRET:test_docker_secret>>`

Sorry to introduce a breaking change, but it seemed better to bite the bullet now, than to add more conditionals.  For the previous image, which uses the old syntax you can use `ortussolutions/commandbox:3.9.1` as the base image.

**Pull request merged**
