### PR TITLE
Update run.sh to support config expansion to env vars

### PR DESCRIPTION
**Pull request by gpickin**

### CODE REVIEW

**Comment by jclausen** [comment]
Please add test coverage (see the compose file and the test script in build/tests). Then I can merge

**Comment by jclausen** [comment]
@gpickin : Did you ever update this with tests? I'd like to get this merged.

**Comment by gpickin** [comment]
No I need to.

**Comment by jclausen** [comment]
Since this is over a year old and hasn't been updated with the requested test coverage, I'm closing this out.   Please re-open a new PR when you're ready.

**Pull request closed without merging**
