### PR TITLE
Fix `lucee5-light-alpine` to use correct Dockerfile

### PR DESCRIPTION
**Pull request by wphampton**

### CODE REVIEW

**Comment by wphampton** [comment]
@jclausen Hello, I hope this patch is helpful. I didn't test it but I was just looking at the pattern of the others and I think this one just needed this small adjustment. -Wes

**Comment by wphampton** [comment]
Hi @jclausen, just wanted to see if there was any timetable for getting this fixed? Thanks a lot for this project!

**Comment by jordanclark** [comment]
+1

**Comment by wphampton** [comment]
Hi @jclausen is there any thing that is holding this up? It seems there is currently a typo in the workflow and this should remedy it. Thanks for your efforts! -Wes

**Comment by wphampton** [comment]
@jclausen Pretty please?

**Pull request merged**
